package gcom.faturamento.conta;

import gcom.arrecadacao.banco.ContaBancaria;
import gcom.atendimentopublico.ligacaoagua.LigacaoAguaSituacao;
import gcom.atendimentopublico.ligacaoesgoto.LigacaoEsgotoSituacao;
import gcom.atendimentopublico.registroatendimento.RegistroAtendimento;
import gcom.cadastro.funcionario.Funcionario;
import gcom.cadastro.imovel.Imovel;
import gcom.cadastro.imovel.ImovelPerfil;
import gcom.cadastro.localidade.Localidade;
import gcom.cobranca.DocumentoTipo;
import gcom.cobranca.parcelamento.Parcelamento;
import gcom.faturamento.FaturamentoGrupo;
import gcom.faturamento.FaturamentoTipo;
import gcom.faturamento.consumotarifa.ConsumoTarifa;
import gcom.faturamento.debito.DebitoCreditoSituacao;
import gcom.seguranca.acesso.usuario.Usuario;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public interface IConta extends Serializable {

	public void setId(Integer id);
	public void setReferencia(Integer referencia);
	public void setImovel(Imovel imovel);
	public void setLote(Short lote);
	public void setSubLote(Short sublote);
	public void setIndicadorCobrancaMulta(Short indicadorCobrancaMulta);
	public void setIndicadorAlteracaoVencimento(Short indicadorAlteracaoVencimento);
	public void setConsumoAgua(Integer consumoAgua);
	public void setConsumoEsgoto(Integer consumoEsgoto);
	public void setConsumoRateioAgua(Integer consumoRateioAgua);
	public void setConsumoRateioEsgoto(Integer consumoRateioEsgoto);
	public void setValorAgua(BigDecimal valorAgua);
	public void setValorEsgoto(BigDecimal  valorEsgoto);
	public void setValorCreditos(BigDecimal valorCreditos);
	public void setPercentualEsgoto(BigDecimal percentualEsgoto);
	public void setDataVencimentoConta(Date dataVencimentoConta);
	public void setDataValidadeConta(Date dataValidadeConta);
	public void setDataInclusao(Date dataInclusao);
	public void setDataRevisao(Date dataRevisao);
	public void setDataRetificacao(Date dataRetificacao);
	public void setDataCancelamento(Date dataCancelamento);
	public void setDataEmissao(Date dataEmissao);
	public void setLigacaoEsgotoSituacao(LigacaoEsgotoSituacao situacao);
	public void setLigacaoAguaSituacao(LigacaoAguaSituacao situacao);
	public void setMotivoNaoEntregaDocumento(MotivoNaoEntregaDocumento motivo);
	public void setLocalidade(Localidade localidade);
	public void setContaMotivoInclusao(ContaMotivoInclusao motivo);
	public void setContaMotivoRevisao(ContaMotivoRevisao motivo);
	public void setContaMotivoRetificacao(ContaMotivoRetificacao motivo);
	public void setContaMotivoCancelamento(ContaMotivoCancelamento motivo);
	public void setFaturamentoTipo(FaturamentoTipo tipo);
	public void setImovelPerfil(ImovelPerfil imovelPerfil);
	public void setRegistroAtendimento(RegistroAtendimento registro);
	public void setConsumoTarifa(ConsumoTarifa tarifa);
	public void setIndicadorDebitoConta(Short indicadorDebitoConta);
	public void setFuncionarioEntrega(Funcionario funcionario);
	public void setFuncionarioLeitura(Funcionario funcionario);
	public void setDebitoCreditoSituacaoAtual(DebitoCreditoSituacao situacao);
	public void setDebitoCreditoSituacaoAnterior(DebitoCreditoSituacao situacao);
	public void setDocumentoTipo(DocumentoTipo tipo);
	public void setContaBancaria(ContaBancaria conta);
	public void setDataVencimentoOriginal(Date DataVencimentoOriginal);
	public void setParcelamento(Parcelamento parcelamento);
	public void setValorImposto(BigDecimal valorImposto);
	public void setUsuario(Usuario usuario);
	public void setNumeroRetificacoes(Integer numeroRetificacoes);
	public void setNumeroFatura(String numeroFatura);
	public void setFaturamentoGrupo(FaturamentoGrupo grupo);
	public void setNumeroLeituraAnterior(Integer numeroLeituraAnterior);
	public void setNumeroLeituraAtual(Integer numeroLeituraAtual);
	public void setValorDebitos(BigDecimal valorDebitos);
	public void setReferenciaContabil(Integer referenciaContabil);

	public Integer getId();
	public Integer getReferencia();
	public Imovel getImovel();
	public Short getLote();
	public Short getSubLote();
	public Short getIndicadorCobrancaMulta();
	public Short getIndicadorAlteracaoVencimento();
	public Integer getConsumoAgua();
	public Integer getConsumoEsgoto();
	public Integer getConsumoRateioAgua();
	public Integer getConsumoRateioEsgoto();
	public BigDecimal getValorAgua();
	public BigDecimal getValorEsgoto();
	public BigDecimal getValorCreditos();
	public BigDecimal getPercentualEsgoto();
	public Date getDataVencimentoConta();
	public Date getDataValidadeConta();
	public Date getDataInclusao();
	public Date getDataRevisao();
	public Date getDataRetificacao();
	public Date getDataCancelamento();
	public Date getDataEmissao();
	public LigacaoEsgotoSituacao getLigacaoEsgotoSituacao();
	public LigacaoAguaSituacao getLigacaoAguaSituacao();
	public MotivoNaoEntregaDocumento getMotivoNaoEntregaDocumento();
	public Localidade getLocalidade();
	public ContaMotivoInclusao getContaMotivoInclusao();
	public ContaMotivoRevisao getContaMotivoRevisao();
	public ContaMotivoRetificacao getContaMotivoRetificacao();
	public ContaMotivoCancelamento getContaMotivoCancelamento();
	public FaturamentoTipo getFaturamentoTipo();
	public ImovelPerfil getImovelPerfil();
	public RegistroAtendimento getRegistroAtendimento();
	public ConsumoTarifa getConsumoTarifa();
	public Short getIndicadorDebitoConta();
	public Funcionario getFuncionarioEntrega();
	public Funcionario getFuncionarioLeitura();
	public DebitoCreditoSituacao getDebitoCreditoSituacaoAtual();
	public DebitoCreditoSituacao getDebitoCreditoSituacaoAnterior();
	public DocumentoTipo getDocumentoTipo();
	public ContaBancaria getContaBancaria();
	public Date getDataVencimentoOriginal();
	public Parcelamento getParcelamento();
	public BigDecimal getValorImposto();
	public Usuario getUsuario();
	public Integer getNumeroRetificacoes();
	public String getNumeroFatura();
	public FaturamentoGrupo getFaturamentoGrupo();
	public Integer getNumeroLeituraAnterior();
	public Integer getNumeroLeituraAtual();
	public BigDecimal getValorDebitos();
	public Integer getReferenciaContabil();
	
	public Conta buildConta(Conta conta);
}
