package gcom.util;

public interface MetodosBatch {
	int ENDERECO_INSERIR_CEP_IMPORTADOS = 1;
	int CONSISTIR_LEITURAS_CALCULAR_CONSUMOS = 2;
	int REGISTRAR_MOVIMENTOS_ARRECADADORES = 3;
	int REGISTRAR_LEITURAS_ANORMALIDADES = 4;
	int GERAR_MOVIMENTO_DEBITO_AUTOMATICO_BANCO = 5;
	int REGERAR_MOVIMENTO_DEBITO_AUTOMATICO_BANCO = 6;
	int GERAR_ARQUIVO_TEXTO_FATURAMENTO = 7;
	int GERAR_RELATORIO_ACOMPANHAMENTO_MOVIMENTO_ARRECADADORES = 8;
	int GERAR_RELATORIO_MAPA_CONTROLE_CONTA = 9;
	int ALTERAR_VENCIMENTO_CONJUNTO_CONTA_CLIENTE = 10;
	int ALTERAR_VENCIMENTO_CONJUNTO_CONTA = 11;
	int ALTERAR_VENCIMENTO_CONJUNTO_CONTA_COLECAO = 12;
	int CANCELAR_CONJUNTO_CONTA = 13;
	int CANCELAR_CONJUNTO_CONTA_CLIENTE = 14;
	int CANCELAR_CONJUNTO_CONTA_POR_GRUPO_FATURAMENTO = 15;
	int RETIFICAR_CONJUNTO_CONTA_POR_GRUPO_FATURAMENTO = 16;
	int RETIFICAR_CONJUNTO_CONTA_COLECAO = 17;
	int ATUALIZAR_LEITURA_ANORMALIDADE_CELULAR_CASO_SISTEMA = 18;
	int INSERIR_DEBITOS_PARA_CONTAS_VALOR_DIFERENTE = 19;
	int GERAR_BOLETIM_MEDICAO = 20;
	int INFORMAR_CONTAS_COBRANCA_EMPRESA = 21;
	int GERAR_BOLSA_AGUA = 22;
}